apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
    service: account-service
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: account-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service-account
  labels:
    account: account-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-v1
  labels:
    app: account-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
      version: v1
  template:
    metadata:
      labels:
        app: account-service
        version: v1
    spec:
      serviceAccountName: account-service-account
      containers:
      - name: account-service
        image: 542247608415.dkr.ecr.ap-south-1.amazonaws.com/account:latest
        imagePullPolicy: Always
        env:
        - name: version
          value: "V1"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: awssecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-v2
  labels:
    app: account-service
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
      version: v2
  template:
    metadata:
      labels:
        app: account-service
        version: v2
    spec:
      serviceAccountName: account-service-account
      containers:
      - name: account-service
        image: 542247608415.dkr.ecr.ap-south-1.amazonaws.com/account:latest
        imagePullPolicy: Always
        env:
        - name: version
          value: "V2"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: awssecret
