kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-viewer-binding
subjects:
- kind: User
  name: EKSkubectlRole
  apiGroup: ""
roleRef:
  kind: Role
  name: EKSkubectlRole
  apiGroup: ""