apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customerinfo
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/customer-gateway
  http:
  - route:
    - destination:
        host: customer-service
        port:
          number: 8080
    