apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service
    service: customer-service
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: customer-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service-account
  labels:
    account: customer-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-v1
  labels:
    app: customer-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
      version: v1
  template:
    metadata:
      labels:
        app: customer-service
        version: v1
    spec:
      serviceAccountName: customer-service-account
      containers:
      - name: customer-service
        image: 542247608415.dkr.ecr.ap-south-1.amazonaws.com/customer:latest
        imagePullPolicy: Always
        env:
        - name: version
          value: "V1"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: awssecret
